#!/bin/bash
#
# Plugin to monitor the queues of a virtual_host in RabbitMQ
#
# Usage: Link or copy into /etc/munin/node.d/
#
# Parameters
#     env.url <url of management plugin>
#     env.queue_warn <warning queuesize>
#     env.queue_crit <critical queuesize>
#
# Magic markers (optional - only used by munin-config and some
# installation scripts):
#
#%# family=auto
#%# capabilities=autoconf

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

# If run with the "config"-parameter, give out information on how the
# graphs should look.

if [ "$1" = "config" ]; then
	QUEUES=$(curl -sS $url/api/queues | jq -r '.[] | .name' | sed 's/[^a-z0-9]\+/_/g')

	QUEUE_WARN=${queue_warn:-100}
	QUEUE_CRIT=${queue_crit:-500}

	# The host name this plugin is for. (Can be overridden to have
	# one machine answer for several)

	# The title of the graph
	echo "graph_title RabbitMQ consumers"
	# Arguments to "rrdtool graph". In this case, tell it that the
	# lower limit of the graph is '0', and that 1k=1000 (not 1024)
	echo 'graph_args --base 1000 -l 0'
	# The Y-axis label
	echo 'graph_vlabel consumers'
	# We want Cur/Min/Avg/Max unscaled (i.e. 0.42 load instead of
	# 420 milliload)
	#echo 'graph_scale no'
	echo 'graph_category RabbitMQ'

	for queue in $QUEUES; do
		echo "$queue.label $queue"
		echo "$queue.warning $QUEUE_WARN"
		echo "$queue.critical $QUEUE_CRIT"
		echo "$queue.info Active consumers for $queue"
	done

	echo 'graph_info Lists active consumers for a queue.'
	# Last, if run with the "config"-parameter, quit here (don't
	# display any data)
	exit 0
fi

# If not run with any parameters at all (or only unknown ones), do the
# real work - i.e. display the data. Almost always this will be
# "value" subfield for every data field.

IFS=$'\n'
for line in $(curl -sS $url/api/queues | jq -c -r '.[] | {name: .name, consumers: .consumers}'); do
	echo -n "$line" | jq -j '.name' | sed 's/[^a-z0-9]\+/_/g'
	echo -n ".value "
	echo -n "$line" | jq -j '.consumers'
	echo ""
done
IFS=$' \t\n'
